// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using DataAccess.Data.DbContext;
using DataAccess.Data.Entities;
using Microsoft.EntityFrameworkCore;


public partial class Attendance_SystemContext : DbContext
{
    public Attendance_SystemContext()
    {
    }

    public Attendance_SystemContext(DbContextOptions<Attendance_SystemContext> options)  : base(options)
    {
    }

    public virtual DbSet<Attendance> Attendances { get; set; }

    public virtual DbSet<Department> Departments { get; set; }

    public virtual DbSet<Employee> Employees { get; set; }

    public virtual DbSet<Sub_Company> Sub_Companies { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Attendance>(entity =>
        {
            entity.HasKey(e => new { e.Emp_Id, e.Att_Date }).HasName("PK__Attendan__7683302DAE97C208");

            entity.Property(e => e.Emp_Id).ValueGeneratedOnAdd();

            entity.HasOne(d => d.Emp).WithMany(p => p.Attendances)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Attendanc__Emp_I__3E52440B");
        });

        modelBuilder.Entity<Department>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Departme__3214EC0799B3CDCB");

            entity.HasOne(d => d.Manager).WithMany(p => p.Departments).HasConstraintName("FK__Departmen__Manag__403A8C7D");

            entity.HasOne(d => d.sub).WithMany(p => p.Departments).HasConstraintName("FK__Departmen__sub_i__3B75D760");
        });

        modelBuilder.Entity<Employee>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Employee__3214EC07874F08C1");

            entity.HasOne(d => d.LineManager).WithMany(p => p.Subordinates)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Employee__Line_M__5AEE82B9");
        });

        OnModelCreatingPartial(modelBuilder);

        modelBuilder.Entity<Sub_Company>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Sub_Comp__3214EC07D1AA35C4");

            entity.HasOne(d => d.CEO).WithMany(p => p.Sub_Companies).HasConstraintName("FK__Sub_Compa__CEO_i__38996AB5");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}