// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using DataAccess.Data.DbContext;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.Data.Entities;

[PrimaryKey("Emp_Id", "Att_Date")]
[Table("Attendance")]
public partial class Attendance : BaseEntity
{
    [Key]
    public int Emp_Id { get; set; }

    [Key]
    public DateOnly Att_Date { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Check_in { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Check_out { get; set; }

    public bool Is_Late { get; set; }

    public bool Is_Absent { get; set; }

    [StringLength(50)]
    public string Status { get; set; }

    [ForeignKey("Emp_Id")]
    [InverseProperty("Attendances")]
    public virtual Employee Emp { get; set; }
}