// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using DataAccess.Data.Entities;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.Data.DbContext;

[Table("Department")]
public partial class Department : BaseEntity
{
    [Key]
    public int Id { get; set; }

    [StringLength(50)]
    public string dept_name { get; set; }

    public int sub_id { get; set; }

    public int? Manager_Id { get; set; }

    [InverseProperty("Dept")]
    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();

    [ForeignKey("Manager_Id")]
    [InverseProperty("Departments")]
    public virtual Employee Manager { get; set; }

    [ForeignKey("sub_id")]
    [InverseProperty("Departments")]
    public virtual Sub_Company sub { get; set; }
}