// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using DataAccess.Data.Entities;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.Data.DbContext;

[Table("Employee")]
public partial class Employee : BaseEntity
{
    [Key]
    public int Id { get; set; }

    [StringLength(30)]
    public string Fname { get; set; }

    [StringLength(30)]
    public string Lname { get; set; }

    public int Emp_Phone { get; set; }

    [StringLength(50)]
    public string Email { get; set; }

    public bool Is_Manager { get; set; }

    [StringLength(50)]
    public string UserName { get; set; }

    [StringLength(50)]
    public string PasswordHash { get; set; }

    public int Dept_Id { get; set; }

    [InverseProperty("Emp")]
    public virtual ICollection<Attendance> Attendances { get; set; } = new List<Attendance>();

    [InverseProperty("Manager")]
    public virtual ICollection<Department> Departments { get; set; } = new List<Department>();

    [ForeignKey("Dept_Id")]
    [InverseProperty("Employees")]
    public virtual Department Dept { get; set; }

    [InverseProperty("CEO")]
    public virtual ICollection<Sub_Company> Sub_Companies { get; set; } = new List<Sub_Company>();
}