// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DataAccess.Data.Entities;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccess.Data.DbContext;

[Table("Sub_Company")]
public partial class Sub_Company : BaseEntity
{
    [Key]
    public int Id { get; set; }

    [StringLength(30)]
    public string Sub_Name { get; set; }

    [StringLength(50)]
    public string Address { get; set; }

    public int? Sub_Phone { get; set; }

    public int CEO_id { get; set; }

    [ForeignKey("CEO_id")]
    [InverseProperty("Sub_Companies")]
    public virtual Employee CEO { get; set; }

    [InverseProperty("sub")]
    public virtual ICollection<Department> Departments { get; set; } = new List<Department>();
}